### ISSUE TITLE
download_attachment method crashes on binary objects

### ISSUE THREAD

**Issue by kerastinell** [mailslurp/mailslurp-client-python#1]
Steps to reproduce:

1. Send any email to MailSlurp that has binary object in attachments. Just for the sake of example, `dd if=/dev/urandom bs=64 count=1 of=attachment.bin` will do.
2. Execute `download_attachment` method on said attachment.

Log:

```
Traceback (most recent call last):
  File "redacted.py", line 60, in <module>
    run()
  File "redacted.py", line 53, in run
    attachment_data = attachments_api.download_attachment(attachment.id, email.id)
  File "/redacted/lib/python3.6/site-packages/mailslurp_client/api/email_controller_api.py", line 264, in download_attachment
    return self.download_attachment_with_http_info(attachment_id, email_id, **kwargs)  # noqa: E501
  File "/redacted/lib/python3.6/site-packages/mailslurp_client/api/email_controller_api.py", line 357, in download_attachment_with_http_info
    collection_formats=collection_formats)
  File "/redacted/lib/python3.6/site-packages/mailslurp_client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/redacted/lib/python3.6/site-packages/mailslurp_client/api_client.py", line 184, in __call_api
    _request_timeout=_request_timeout)
  File "/redacted/lib/python3.6/site-packages/mailslurp_client/api_client.py", line 377, in request
    headers=headers)
  File "/redacted/lib/python3.6/site-packages/mailslurp_client/rest.py", line 239, in GET
    query_params=query_params)
  File "/redacted/lib/python3.6/site-packages/mailslurp_client/rest.py", line 223, in request
    r.data = r.data.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte
```

[Documentation](https://github.com/mailslurp/mailslurp-client-python/blob/master/docs/EmailControllerApi.md#download_attachment) for download_attachment says:

> Get email attachment **bytes**

but the method itself returns string for some reason:

> Return type
> str

**Comment by jackmahoney** [comment]
Interesting. Thank you for reporting this. I will try to investigate.

**Comment by jackmahoney** [comment]
Hi @kerastinell we have now added a downloadBase64 endpoint to the python client to work around the binary issues. Thanks for alerting us.

Please use the latest version on PYPI for the new endpoint. https://pypi.org/project/mailslurp-client/
